[project]
name = "functions"
version = "0.1.0"
description = "Lambda functions"
requires-python = "==3.11.*"
dependencies = [
    "requests>=2.31.0",
    "boto3>=1.28.0",
    "python-dateutil>=2.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"